### ISSUE TITLE
Regression: Full timestamp on https://plugins.qgis.org/plugins/

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS-Django#376]
Something must have changed, currently the full timestamp including miiliseconds is displayed on https://plugins.qgis.org/plugins/:

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/44afbc15-84c1-4e1c-a974-6eb0c8ab7e83)

IIRC also the local timezone was displayed before this change.

**Comment by Xpirix** [comment]
Dear @pathmapper ,

I see that it has been fixed. I'm able to see the correct format now.

Regards.

![image](https://github.com/qgis/QGIS-Django/assets/43842786/b0d9d525-b6b3-417a-a175-3072eb2180ec)

**Comment by pathmapper** [comment]
I'm still seeing this on a notebook with Firefox and Chrome. On mobile everthing is fine. 

Maybe my timezone could not be detected for some reason and thus the conversion in local timezone is failing and therefor the full timestamp is displayed?

**Comment by Xpirix** [comment]
You're right, this might be possible. This issue occurred already in the past (https://github.com/qgis/QGIS-Django/pull/315#issuecomment-1869307984) because of an old version of `local_timezone.js` served by the server. Currently, the new version that is used is `local_timezone-1.0.js`.

Could you please try to clear the browser cache and see if this still occurs?

I will try to reproduce this on my side.

**Comment by pathmapper** [comment]
> Could you please try to clear the browser cache and see if this still occurs?

Unfortunately the issue is still there, I'm seeing this on three different machines. 

Thanks for taking a look!

**Comment by Xpirix** [comment]
@pathmapper 

I was able to reproduce the issue. Seems like the file `local_timezone-1.0.js` was not found on the server. It should be fixed now.

Regards.

**Comment by pathmapper** [comment]
@Xpirix great, confirmed the issue is fixed, thanks a lot 🎉
